### ISSUE TITLE
Further lab materials 

### ISSUE THREAD

**Issue by EliotZhu** [tlbbd-spring2018/lab_10#1]
This course is particular useful for me to understand the TMLE procedure. I wonder if the material after lab 10 are public available?

Thank you.

**Comment by nhejazi** [comment]
Hello @Elio-z --- thanks for your interest in the course materials; we're very glad to hear that posting these publicly has been helpful. Unfortunately, after lab 10, the lab component of the course changed direction --- focusing on providing time for students to work on final course projects rather than presenting new material --- and so there are no further laboratory materials to be made publicly available. We hope that future offerings of this course will build on what we made available here.
